version: '3'
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.4.2"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk
    environment:
      - discovery.type=single-node
  kibana:
    image: "docker.elastic.co/kibana/kibana:7.4.2"
    ports:
      - "5601:5601"
    networks:
      - elk
  filebeat:
    image: "docker.elastic.co/beats/filebeat:7.4.2"
    networks:
      - elk
    environment:
      - strict.perms=false
      - output.elasticsearch.hosts=["elasticsearch:9200"]
    volumes:
       - $(pwd)/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
networks:
  elk:
     driver: bridge